name: aden_fe
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  http: ^1.2.1
  get_it: ^7.7.0
  dartz: ^0.10.1
  flutter_secure_storage: ^9.0.0
  flutter_bloc: ^8.1.5
  injectable: ^2.4.1
  crypto: ^3.0.3
  loading_animation_widget: ^1.2.1
  package_info_plus: ^8.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  iconify_flutter: ^0.0.5
  google_fonts: ^6.2.1
  geolocator: ^12.0.0
  cached_network_image: ^3.4.0
  geocoding: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/